// Do not edit this file!
// The content are generated automatically
import '@busy-hour/blaze';
import type {
  ActionsExtractor,
  EventsExtractor,
} from '@busy-hour/blaze-types/dist/types/types/internal';
import ocr from '../services/ocr';

declare module '@busy-hour/blaze' {
  export interface ActionCallRecord extends ActionsExtractor<typeof ocr> {}

  export interface EventCallRecord extends EventsExtractor<typeof ocr> {}
}
